format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$terraform\
$fill\
$aws\
$cmd_duration $jobs $time\
$line_break\
$character"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[fill]
symbol = " "

# Replace the "❯" symbol in the prompt with "➜"
[character] 
success_symbol = "[➜](bold green)"
error_symbol   = "[➜](bold red)" 

[aws]
format = 'aws [$symbol($profile )(\($region\) )]($style)'
symbol = "  "
style = "bold yellow"

[aws.region_aliases]
ap-southeast-2 = "au"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " "
read_only_style = "red"
home_symbol = "~"
style = "white bold dimmed"

[docker_context]
symbol = " "

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_metrics]
format = "${all_status}"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true

[terraform]
format = "[$symbol$version $workspace]($style)"
symbol = "行"
version_format = "v${raw}"
style = "105"

